export const sustainableClothingData = [
  {
    name: "Organic Cotton Tee",
    company: "Evergreen Apparel",
    price: 28,
    fabric: "Cotton",
    rating: 4.6,
    distance: 2.1,
  },
  {
    name: "Recycled Denim Jeans",
    company: "Renew Threads",
    price: 72,
    fabric: "Cotton",
    rating: 4.8,
    distance: 3.4,
  },
  {
    name: "Hemp Everyday Shorts",
    company: "EarthWear",
    price: 45,
    fabric: "Cotton",
    rating: 4.5,
    distance: 1.9,
  },
  {
    name: "Lyocell Flowy Dress",
    company: "EcoChic",
    price: 68,
    fabric: "Tencel Lyocell",
    rating: 4.7,
    distance: 4.0,
  },
  {
    name: "Merino Wool Sweater",
    company: "Northbound Knit",
    price: 98,
    fabric: "Wool",
    rating: 4.9,
    distance: 2.8,
  },
  {
    name: "Upcycled Patch Jacket",
    company: "ReForm Studios",
    price: 110,
    fabric: "Mixed Fabrics",
    rating: 4.4,
    distance: 5.1,
  },
  {
    name: "Bamboo Lounge Pants",
    company: "GreenNest",
    price: 52,
    fabric: "Bamboo",
    rating: 4.6,
    distance: 2.3,
  },
  {
    name: "Organic Linen Button-Up",
    company: "PureLine",
    price: 64,
    fabric: "Linen",
    rating: 4.5,
    distance: 3.0,
  },
  {
    name: "Recycled Fleece Hoodie",
    company: "LoopWear",
    price: 75,
    fabric: "Polyester",
    rating: 4.3,
    distance: 4.4,
  },
  {
    name: "Hemp Athletic Tank",
    company: "NaturFlex",
    price: 33,
    fabric: "Hemp",
    rating: 4.2,
    distance: 1.6,
  },
  {
    name: "Organic Cotton Cargo Pants",
    company: "UrbanSprout",
    price: 58,
    fabric: "Cotton",
    rating: 4.6,
    distance: 5.7,
  },
  {
    name: "Recycled Nylon Windbreaker",
    company: "Circulate Co.",
    price: 82,
    fabric: "Nylon",
    rating: 4.4,
    distance: 6.2,
  },
  {
    name: "Wool Blend Scarf",
    company: "Cascade Loom",
    price: 42,
    fabric: "Wool",
    rating: 4.8,
    distance: 1.2,
  },
  {
    name: "Organic Cotton Socks (3-Pack)",
    company: "BareBasics",
    price: 18,
    fabric: "Cotton",
    rating: 4.7,
    distance: 0.8,
  },
  {
    name: "Tencel High-Waisted Skirt",
    company: "EcoChic",
    price: 55,
    fabric: "Tencel Lyocell",
    rating: 4.5,
    distance: 4.0,
  },
  {
    name: "Upcycled Leather Tote",
    company: "Revive Goods",
    price: 120,
    fabric: "Leather",
    rating: 4.9,
    distance: 6.5,
  },
  {
    name: "Recycled Polyester Puffer Vest",
    company: "LoopWear",
    price: 95,
    fabric: "Polyester",
    rating: 4.1,
    distance: 3.9,
  },
  {
    name: "Organic Cotton Hoodie",
    company: "Evergreen Apparel",
    price: 60,
    fabric: "Cotton",
    rating: 4.6,
    distance: 2.1,
  },
  {
    name: "Hemp Oversized Tee",
    company: "EarthWear",
    price: 38,
    fabric: "Cotton",
    rating: 4.3,
    distance: 1.9,
  },
  {
    name: "Recycled Wool Coat",
    company: "Northbound Knit",
    price: 150,
    fabric: "Wool",
    rating: 4.8,
    distance: 2.8,
  },
  {
    name: "Organic Linen Shorts",
    company: "PureLine",
    price: 48,
    fabric: "Linen",
    rating: 4.5,
    distance: 3.0,
  },
  {
    name: "Recycled Running Leggings",
    company: "NaturFlex",
    price: 54,
    fabric: "Polyester",
    rating: 4.4,
    distance: 1.6,
  },
  {
    name: "Bamboo Long Sleeve Top",
    company: "GreenNest",
    price: 40,
    fabric: "Bamboo",
    rating: 4.6,
    distance: 2.3,
  },
  {
    name: "Organic Cotton Beanie",
    company: "BareBasics",
    price: 22,
    fabric: "Cotton",
    rating: 4.7,
    distance: 0.8,
  },
  {
    name: "Upcycled Denim Skirt",
    company: "ReForm Studios",
    price: 50,
    fabric: "Denim",
    rating: 4.5,
    distance: 5.1,
  },
  {
    name: "Recycled Polyester Rain Jacket",
    company: "Circulate Co.",
    price: 110,
    fabric: "Polyester",
    rating: 4.3,
    distance: 6.2,
  },
  {
    name: "Organic Cotton Joggers",
    company: "UrbanSprout",
    price: 52,
    fabric: "Cotton",
    rating: 4.6,
    distance: 5.7,
  },
  {
    name: "Hemp Work Shirt",
    company: "EarthWear",
    price: 62,
    fabric: "Hemp",
    rating: 4.4,
    distance: 1.9,
  },
  {
    name: "Tencel Everyday Blouse",
    company: "EcoChic",
    price: 47,
    fabric: "Tencel Lyocell",
    rating: 4.5,
    distance: 4.0,
  },
  {
    name: "Recycled PET Athletic Jacket",
    company: "LoopWear",
    price: 88,
    fabric: "Polyester",
    rating: 4.4,
    distance: 4.4,
  }
];
